### ISSUE TITLE
Code review changes

### ISSUE THREAD

**Issue by duongand** [Tu-Vien-Van-Phat-Danh/tu-vien-van-phat-danh.github.io#2]
1. [Rename classes one, two, and three to be more specific what the class is referring to](https://github.com/Tu-Vien-Van-Phat-Danh/tu-vien-van-phat-danh.github.io/blob/ea734de7ce4a6a9b97f8c394c805d558a283e1d5/index.html#L14C17-L14C17)
2. [Need to remove inline CSS styling and put into a class that the class can reference to](https://github.com/Tu-Vien-Van-Phat-Danh/tu-vien-van-phat-danh.github.io/blob/ea734de7ce4a6a9b97f8c394c805d558a283e1d5/index.html#L55)

**Comment by noraacode** [comment]
Done
